"""
LESSON: The Complete ML Workflow
=================================
This lesson walks through all 8 steps of the ML workflow on a concrete
student grade prediction problem. After this lesson you will be able to
execute the full pipeline from raw data to evaluated model.

Real engineering context: The same 8-step workflow applies whether you
are predicting student grades, equipment failure, energy consumption, or
chemical yield. The steps never change — only the data and model differ.

Steps covered:
  1. Define the problem
  2. Collect / load data
  3. Explore the data (EDA)
  4. Preprocess (handle missing values, scale features)
  5. Split data (train/test)
  6. Train model
  7. Evaluate (MAE, MSE, R²)
  8. Interpret results
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

np.random.seed(0)

# ============================================================
# STEP 1: DEFINE THE PROBLEM
# ============================================================
print("=" * 60)
print("STEP 1: Define the Problem")
print("=" * 60)
print("""
PROBLEM: Predict a student's final grade (0–100) from:
  - study_hours_per_week   (numerical, continuous)
  - attendance_pct         (numerical, continuous, 0–100)
  - prev_grade             (numerical, previous semester grade)
  - tutoring_sessions      (numerical, discrete count)

Why this problem?
  → A university wants to identify at-risk students EARLY
    (before the final exam) so they can intervene.

Type of ML problem:
  → SUPERVISED LEARNING (we have historical grades to learn from)
  → REGRESSION (final grade is a continuous number 0–100)

Success metric:
  → MAE ≤ 5 points (we want predictions within 5 grade points)
  → R² ≥ 0.80 (explain at least 80% of grade variance)
""")

# ============================================================
# STEP 2: COLLECT / LOAD DATA
# ============================================================
print("=" * 60)
print("STEP 2: Collect / Load Data")
print("=" * 60)

# WHY synthetic data: we generate data that follows a realistic relationship
# so we can verify the model learns it. In practice you'd load a CSV:
#   df = pd.read_csv("student_records.csv")

n_students = 400

study_hours      = np.random.uniform(1, 20, n_students)
attendance_pct   = np.random.uniform(50, 100, n_students)
prev_grade       = np.random.uniform(40, 95, n_students)
tutoring         = np.random.randint(0, 10, n_students)

# True relationship: grade depends on all 4 features + noise
# This simulates data generated by real-world processes
noise = np.random.normal(0, 5, n_students)
final_grade = (
    2.1 * study_hours        # More study = better grade
    + 0.25 * attendance_pct  # Attendance correlates with grade
    + 0.35 * prev_grade      # Prior performance predicts future
    + 1.5 * tutoring         # Tutoring helps
    + 5.0                    # Intercept
    + noise
)
# Clip to realistic range [0, 100]
final_grade = np.clip(final_grade, 0, 100)

# Deliberately inject some missing values to make it realistic
# (10 random students are missing attendance data)
missing_idx = np.random.choice(n_students, 10, replace=False)
attendance_with_nan = attendance_pct.astype(float).copy()
attendance_with_nan[missing_idx] = np.nan

# Build a DataFrame — the most common format for tabular data
df = pd.DataFrame({
    "study_hours":    study_hours,
    "attendance_pct": attendance_with_nan,
    "prev_grade":     prev_grade,
    "tutoring":       tutoring,
    "final_grade":    final_grade
})

print(f"\nDataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"\nFirst 5 rows:")
print(df.head().round(2))

# ============================================================
# STEP 3: EXPLORE THE DATA (EDA)
# ============================================================
print("\n" + "=" * 60)
print("STEP 3: Explore the Data (EDA)")
print("=" * 60)

# WHY EDA: "Garbage in, garbage out." Understanding your data BEFORE
# modeling prevents many costly mistakes. Look for: ranges, missing values,
# correlations, outliers.

print("\n--- Basic Statistics ---")
print(df.describe().round(2))

print("\n--- Missing Values ---")
missing = df.isnull().sum()
print(missing[missing > 0])
print(f"  → attendance_pct has {missing['attendance_pct']} missing values ({missing['attendance_pct']/len(df)*100:.1f}%)")
print("  → We will handle this in Step 4 (imputation)")

print("\n--- Correlation with Final Grade ---")
# WHY correlation: Features strongly correlated with the target are likely
# to be informative. Weakly correlated features may not help.
correlations = df.corr()["final_grade"].sort_values(ascending=False)
print(correlations.round(3))
print("\n  → study_hours has highest correlation: more study → higher grade")
print("  → All features show positive correlation with final grade")

print("\n--- Grade Distribution ---")
print(f"  Mean grade:   {df['final_grade'].mean():.1f}")
print(f"  Std dev:      {df['final_grade'].std():.1f}")
print(f"  Min grade:    {df['final_grade'].min():.1f}")
print(f"  Max grade:    {df['final_grade'].max():.1f}")
q25, q75 = df['final_grade'].quantile([0.25, 0.75])
print(f"  Q1/Q3:        {q25:.1f} / {q75:.1f}")

# ============================================================
# STEP 4: PREPROCESS
# ============================================================
print("\n" + "=" * 60)
print("STEP 4: Preprocess the Data")
print("=" * 60)

# WHY preprocessing:
#   - Missing values: sklearn models cannot handle NaN by default
#   - Feature scaling: many algorithms are sensitive to feature magnitude
#     (e.g., if study_hours is 0–20 and attendance is 50–100, the model
#     might weight them differently just because of scale)

# Separate features from target
X = df.drop("final_grade", axis=1)
y = df["final_grade"].values

print(f"\nFeature matrix X shape: {X.shape}")
print(f"Target vector y shape:  {y.shape}")

# --- Handle missing values ---
print("\n--- 4a: Imputing Missing Values ---")
print("Strategy: replace NaN with the COLUMN MEAN")
print("WHY mean imputation: simple, fast, works well when data is missing at random")
print("Alternative: KNNImputer (use similar students to estimate missing attendance)")

imputer = SimpleImputer(strategy="mean")
# fit_transform on the full X here for demonstration
# (In Step 5, we'll do this properly on train set only!)
X_imputed = imputer.fit_transform(X)
print(f"Missing values after imputation: {np.isnan(X_imputed).sum()}")

# --- Feature scaling ---
print("\n--- 4b: Scaling Features (StandardScaler) ---")
print("StandardScaler transforms each feature to: mean=0, std=1")
print("Formula: x_scaled = (x - mean) / std")
print("\nWHY scale: Ensures no feature dominates simply because of its numeric range")
print("  study_hours range: 1–20   (small numbers)")
print("  attendance_pct range: 50–100 (larger numbers)")
print("  Without scaling, the model might artificially weight attendance more")

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

print(f"\nBefore scaling — study_hours:   mean={X_imputed[:,0].mean():.2f}, std={X_imputed[:,0].std():.2f}")
print(f"After scaling  — study_hours:   mean={X_scaled[:,0].mean():.4f}, std={X_scaled[:,0].std():.4f}")
print(f"Before scaling — attendance:    mean={X_imputed[:,1].mean():.2f}, std={X_imputed[:,1].std():.2f}")
print(f"After scaling  — attendance:    mean={X_scaled[:,1].mean():.4f}, std={X_scaled[:,1].std():.4f}")
print("  → All features now have comparable scale (mean≈0, std≈1)")

# ============================================================
# STEP 5: SPLIT DATA
# ============================================================
print("\n" + "=" * 60)
print("STEP 5: Train/Test Split")
print("=" * 60)

# WHY split AFTER preprocessing (fitting): If you fit the scaler on all
# data before splitting, test data statistics "leak" into training.
# Correct order: split FIRST, then fit scaler on train only.
# (In Module 2, Pipelines handle this automatically and safely.)

print("\nIMPORTANT: In this lesson, we split the raw data first, then preprocess.")
print("The imputer and scaler below are fit ONLY on training data.")

X_raw = df.drop("final_grade", axis=1).values
y_vals = df["final_grade"].values

X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X_raw, y_vals, test_size=0.2, random_state=42
)

# Now fit preprocessing ONLY on training data, apply to both
imp = SimpleImputer(strategy="mean")
X_train_imp = imp.fit_transform(X_train_raw)    # fit+transform on train
X_test_imp  = imp.transform(X_test_raw)          # transform only on test

sc = StandardScaler()
X_train = sc.fit_transform(X_train_imp)          # fit+transform on train
X_test  = sc.transform(X_test_imp)               # transform only on test

print(f"\n  Training samples: {X_train.shape[0]} ({X_train.shape[0]/len(y_vals)*100:.0f}%)")
print(f"  Test samples:     {X_test.shape[0]}  ({X_test.shape[0]/len(y_vals)*100:.0f}%)")
print("\n  Rule of thumb: 80/20 split for moderate datasets (>1000 samples: 90/10 is fine)")

# ============================================================
# STEP 6: TRAIN MODEL
# ============================================================
print("\n" + "=" * 60)
print("STEP 6: Train Model")
print("=" * 60)

# WHY LinearRegression: our target is continuous and we suspect a roughly
# linear relationship between study effort and grades (more study = better grade).
# For a first model, always start simple.

model = LinearRegression()
model.fit(X_train, y_train)

print("\nModel trained! model.fit() solved the least-squares problem.")
print(f"\nLearned coefficients (for scaled features):")
feature_names = ["study_hours", "attendance_pct", "prev_grade", "tutoring"]
for name, coeff in zip(feature_names, model.coef_):
    direction = "↑" if coeff > 0 else "↓"
    print(f"  {name:20s}: {coeff:+.3f}  {direction}")
print(f"  {'intercept':20s}: {model.intercept_:.3f}")
print("\n  → Positive coefficients: higher value → higher predicted grade")
print("  → All features contribute positively (as expected from our data generation)")

# ============================================================
# STEP 7: EVALUATE
# ============================================================
print("\n" + "=" * 60)
print("STEP 7: Evaluate Model Performance")
print("=" * 60)

# WHY multiple metrics: Each tells a different story.
#   MAE  = average absolute error (in original units — grade points)
#   RMSE = root mean squared error (penalizes big mistakes more)
#   R²   = proportion of variance explained (0 = useless, 1 = perfect)

y_pred_train = model.predict(X_train)
y_pred_test  = model.predict(X_test)

mae_train  = mean_absolute_error(y_train, y_pred_train)
mae_test   = mean_absolute_error(y_test,  y_pred_test)
mse_test   = mean_squared_error(y_test,   y_pred_test)
rmse_test  = np.sqrt(mse_test)
r2_train   = r2_score(y_train, y_pred_train)
r2_test    = r2_score(y_test,  y_pred_test)

print(f"\n{'Metric':<30} {'Train':>10} {'Test':>10}")
print("-" * 52)
print(f"{'MAE (grade points)':30} {mae_train:>10.2f} {mae_test:>10.2f}")
print(f"{'RMSE (grade points)':30} {'n/a':>10} {rmse_test:>10.2f}")
print(f"{'R² (0=bad, 1=perfect)':30} {r2_train:>10.4f} {r2_test:>10.4f}")

print(f"\nInterpretation:")
print(f"  → Average prediction error: {mae_test:.1f} grade points")
if mae_test <= 5:
    print(f"  ✓ Below our target of 5 points — model meets requirements!")
else:
    print(f"  ✗ Above our 5-point target — consider more features or a different model")

# Check for overfitting: big gap between train and test R² signals overfitting
r2_gap = r2_train - r2_test
print(f"\n  Train R²: {r2_train:.4f}, Test R²: {r2_test:.4f}")
if r2_gap < 0.05:
    print(f"  ✓ Small train/test R² gap ({r2_gap:.4f}) — no overfitting detected")
else:
    print(f"  ⚠ Large train/test R² gap ({r2_gap:.4f}) — possible overfitting")

# ============================================================
# STEP 8: INTERPRET RESULTS
# ============================================================
print("\n" + "=" * 60)
print("STEP 8: Interpret Results")
print("=" * 60)

print("""
WHAT DID THE MODEL LEARN?
  The model found that study_hours, attendance_pct, prev_grade, and
  tutoring_sessions all positively predict the final grade — exactly
  what the underlying data generation assumed.

WHAT WOULD WE DO NEXT?
  1. Feature engineering: add interaction terms (study_hours × attendance)?
  2. Try a more complex model (Ridge, GradientBoosting) if R² is too low
  3. Collect more features (assignment scores, sleep hours, stress level)
  4. Deploy: run model weekly on current students to flag at-risk students

ACTION ENABLED:
  Students with predicted grade < 60 get an automated email from advisor
  → Early intervention can raise final grades by 5–15 points (research shows)
""")

# Demonstrate a prediction for a real student
print("--- Sample Predictions for 3 Hypothetical Students ---")
students = [
    {"study_hours": 15, "attendance_pct": 95, "prev_grade": 88, "tutoring": 5},
    {"study_hours": 4,  "attendance_pct": 60, "prev_grade": 55, "tutoring": 0},
    {"study_hours": 10, "attendance_pct": 80, "prev_grade": 72, "tutoring": 2},
]
labels = ["High achiever", "At-risk student", "Average student"]

for student, label in zip(students, labels):
    raw = np.array([[student["study_hours"], student["attendance_pct"],
                     student["prev_grade"], student["tutoring"]]])
    imputed = imp.transform(raw)
    scaled  = sc.transform(imputed)
    pred    = model.predict(scaled)[0]
    flag    = " ⚠ INTERVENE" if pred < 60 else " ✓ On track"
    print(f"  {label:18s}: predicted grade = {pred:.1f}{flag}")

print("\n" + "=" * 60)
print("WORKFLOW COMPLETE — You just ran the full ML pipeline!")
print("=" * 60)
print("\nNext: 03_data_and_features.py — deep dive into feature engineering")
