"""
Sklearn Pipelines: The Right Way to Build ML Systems
=====================================================
A Pipeline chains preprocessing steps + a final estimator into
one single object that behaves exactly like any other estimator.

Without Pipeline:
  scaler.fit(X_train)
  X_train_s = scaler.transform(X_train)
  model.fit(X_train_s, y_train)
  X_test_s = scaler.transform(X_test)   ← easy to forget!
  y_pred = model.predict(X_test_s)

  GridSearchCV would also need manual handling... messy and error-prone.

With Pipeline:
  pipe = Pipeline([('scaler', StandardScaler()), ('model', Ridge())])
  pipe.fit(X_train, y_train)            ← fits scaler then model
  y_pred = pipe.predict(X_test)         ← scales then predicts
  GridSearchCV(pipe, ...)               ← handles everything!
"""

import numpy as np
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.model_selection import (
    train_test_split, cross_val_score, GridSearchCV
)
from sklearn.datasets import make_regression, make_classification
from sklearn.metrics import r2_score
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

np.random.seed(42)

X_reg, y_reg = make_regression(n_samples=300, n_features=10, noise=20, random_state=42)
X_cls, y_cls = make_classification(n_samples=300, n_features=10, random_state=42)

X_tr_r, X_te_r, y_tr_r, y_te_r = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)
X_tr_c, X_te_c, y_tr_c, y_te_c = train_test_split(X_cls, y_cls, test_size=0.2, random_state=42)

# Add missing values to demonstrate imputation in pipeline
X_tr_r_missing = X_tr_r.copy()
X_tr_r_missing[np.random.choice(len(X_tr_r), 20), np.random.choice(10, 20)] = np.nan
X_te_r_missing = X_te_r.copy()
X_te_r_missing[np.random.choice(len(X_te_r), 5), np.random.choice(10, 5)] = np.nan

# ===========================================================================
# PART 1: Building Pipelines
# ===========================================================================
print("=" * 60)
print("PART 1: Building Pipelines")
print("=" * 60)

print("""
Pipeline([('name1', transformer1), ('name2', transformer2), ..., ('name_n', estimator)])

Rules:
  - All steps except the last must implement fit() AND transform()
  - Last step must implement fit() (and predict() for supervised learning)
  - Step names must be unique
  - Use descriptive names: 'imputer', 'scaler', 'pca', 'model'
""")

# Simple regression pipeline
reg_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler',  StandardScaler()),
    ('ridge',   Ridge(alpha=1.0)),
])

reg_pipe.fit(X_tr_r_missing, y_tr_r)
r2 = r2_score(y_te_r, reg_pipe.predict(X_te_r_missing))
print(f"Regression Pipeline (Impute → Scale → Ridge)  R²: {r2:.4f}")

# Classification pipeline  
cls_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('rf',     RandomForestClassifier(n_estimators=50, random_state=42)),
])
cls_pipe.fit(X_tr_c, y_tr_c)
print(f"Classification Pipeline (Scale → RandomForest) Acc: {cls_pipe.score(X_te_c, y_te_c):.4f}")

# make_pipeline: shortcut (auto-names from class names, lowercased)
poly_pipe = make_pipeline(
    StandardScaler(),
    PolynomialFeatures(degree=2, include_bias=False),
    Ridge(alpha=1.0),
)
poly_pipe.fit(X_tr_r, y_tr_r)
print(f"make_pipeline (Scale → Poly → Ridge)           R²: {r2_score(y_te_r, poly_pipe.predict(X_te_r)):.4f}")

print("\nPipeline step names (auto-generated by make_pipeline):")
for name, step in poly_pipe.steps:
    print(f"  '{name}': {type(step).__name__}")

# ===========================================================================
# PART 2: Accessing Steps Inside a Pipeline
# ===========================================================================
print("\n" + "=" * 60)
print("PART 2: Accessing Pipeline Internals")
print("=" * 60)

# Access via named_steps
print(f"Scaler mean (first 3 features): {reg_pipe.named_steps['scaler'].mean_[:3].round(4)}")
print(f"Ridge alpha: {reg_pipe.named_steps['ridge'].alpha}")
print(f"Ridge coefficients (first 5): {reg_pipe.named_steps['ridge'].coef_[:5].round(4)}")

# Get + set params: use step_name__param_name
print(f"\nPipeline params (excerpt):")
params = reg_pipe.get_params()
for k, v in list(params.items())[:6]:
    print(f"  {k}: {v}")

# Set a param
reg_pipe.set_params(ridge__alpha=10.0)
print(f"\nAfter set_params(ridge__alpha=10.0):")
print(f"  ridge alpha: {reg_pipe.named_steps['ridge'].alpha}")

# ===========================================================================
# PART 3: Data Leakage — Why Pipelines Prevent It
# ===========================================================================
print("\n" + "=" * 60)
print("PART 3: Data Leakage — Why Pipelines Save You")
print("=" * 60)

print("""
DATA LEAKAGE: when information from test data "leaks" into training.
The model appears to perform well but fails in production.

Common leakage scenario:
  scaler.fit_transform(X_ALL)       ← scaler "sees" test data!
  X_train, X_test = split(X_ALL_scaled)
  model.fit(X_train)
  model.score(X_test)               ← test data already influenced the scaler

This is like a student seeing exam answers while studying.
The scaler's mean/std are now biased toward the test distribution.

Pipeline with cross_val_score prevents leakage:
  - Each CV fold fits the scaler ONLY on that fold's training subset
  - Test fold is scaled using those training-only statistics
  - Every step in the pipeline is refitted for each fold
""")

# Demonstrate leakage effect
def leaky_cv(X, y, model, cv=5):
    """WRONG: fit scaler on ALL data before CV."""
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)  # ← LEAKS TEST DATA
    scores = cross_val_score(model, X_scaled, y, cv=cv, scoring='r2')
    return scores

def pipeline_cv(X, y, cv=5):
    """CORRECT: use Pipeline with cross_val_score."""
    pipe = Pipeline([('scaler', StandardScaler()), ('ridge', Ridge())])
    scores = cross_val_score(pipe, X, y, cv=cv, scoring='r2')
    return scores

leaky_scores   = leaky_cv(X_reg, y_reg, Ridge())
pipeline_scores = pipeline_cv(X_reg, y_reg)

print(f"Leaky CV    mean R²: {leaky_scores.mean():.4f} ± {leaky_scores.std():.4f}  ← optimistically biased")
print(f"Pipeline CV mean R²: {pipeline_scores.mean():.4f} ± {pipeline_scores.std():.4f}  ← honest estimate")

# ===========================================================================
# PART 4: GridSearchCV With Pipeline
# ===========================================================================
print("\n" + "=" * 60)
print("PART 4: GridSearchCV With a Pipeline")
print("=" * 60)

print("""
Pipeline hyperparameter naming convention:
  step_name__parameter_name

Example:
  pipe = Pipeline([('poly', PolynomialFeatures()), ('ridge', Ridge())])
  param_grid = {
      'poly__degree': [1, 2, 3],
      'ridge__alpha':  [0.1, 1.0, 10.0]
  }
  GridSearchCV(pipe, param_grid, cv=5)
  → tries all combinations: 3 × 3 = 9 configurations
  → each tested with 5-fold CV
  → picks the best without leakage!
""")

search_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler',  StandardScaler()),
    ('ridge',   Ridge()),
])

param_grid = {
    'imputer__strategy': ['mean', 'median'],
    'ridge__alpha':      [0.01, 0.1, 1.0, 10.0, 100.0],
}

gs = GridSearchCV(
    search_pipe, param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=0
)
gs.fit(X_tr_r_missing, y_tr_r)

print(f"Best params:  {gs.best_params_}")
print(f"Best CV R²:   {gs.best_score_:.4f}")
print(f"Test R²:      {r2_score(y_te_r, gs.predict(X_te_r_missing)):.4f}")

# ===========================================================================
# PART 5: Pipeline With PCA (Dimensionality Reduction)
# ===========================================================================
print("\n" + "=" * 60)
print("PART 5: Pipeline With Dimensionality Reduction")
print("=" * 60)

print("""
PCA (Principal Component Analysis) is a common preprocessing step:
  - Reduces feature count while preserving variance
  - Removes multicollinearity (correlated features)
  - Useful before Linear models (faster) or visualization

Pipeline: Scale → PCA → Model
""")

pca_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('pca',    PCA(n_components=5)),   # reduce 10 features to 5
    ('ridge',  Ridge(alpha=1.0)),
])
pca_pipe.fit(X_tr_r, y_tr_r)

explained = pca_pipe.named_steps['pca'].explained_variance_ratio_
print(f"PCA: 5 components explain {explained.sum()*100:.1f}% of variance")
print(f"  Per component: {explained.round(3)}")
print(f"Pipeline R²: {r2_score(y_te_r, pca_pipe.predict(X_te_r)):.4f}")

print("""
===========================================
KEY TAKEAWAYS
===========================================
1. Pipeline: chain steps, last step is estimator, rest are transformers
2. Fit automatically fits each step then passes output to next step
3. Prevents data leakage: each CV fold refits ALL steps fresh
4. Step hyperparameters: step_name__param_name for get/set
5. Works seamlessly with GridSearchCV and cross_val_score
6. Use make_pipeline() for quick pipelines with auto-naming
7. Always save the full PIPELINE (includes scaler) for deployment

Next: exercises.py — Practice sklearn API and pipelines
""")
