"""
Capstone Project Starter Template
===================================
Predictive Failure Detection System

Your task: Build a complete ML pipeline to predict machine failures
from industrial sensor data.

Fill in every TODO section. Do NOT look at the reference solution
until you have genuinely attempted each section.

Dataset: industrial_sensor_train.csv and industrial_sensor_test.csv
Generated by: generate_capstone_data.py (run it first!)

Scoring Rubric (200 points total):
  Section 1: Data Exploration        [30 pts]
  Section 2: Preprocessing           [20 pts]
  Section 3: Classical ML            [40 pts]
  Section 4: Deep Learning (MLP)     [50 pts]
  Section 5: Evaluation & Comparison [30 pts]
  Section 6: Interpretation          [30 pts]
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.svm import SVC
from sklearn.metrics import (
    classification_report, confusion_matrix,
    mean_squared_error, r2_score, f1_score
)
from pathlib import Path

# Paths
HERE     = Path(__file__).resolve().parent
DATA_DIR = HERE.parent / "datasets"
OUT_DIR  = HERE / "output"
OUT_DIR.mkdir(exist_ok=True, parents=True)

# ============================================================
# STEP 0: Load Data (already done for you)
# ============================================================
print("Loading capstone dataset...")

train_path = DATA_DIR / "industrial_sensor_train.csv"
test_path  = DATA_DIR / "industrial_sensor_test.csv"

if not train_path.exists():
    print("ERROR: Dataset not found. Please run generate_capstone_data.py first!")
    print(f"  Expected: {train_path}")
    raise SystemExit(1)

df_train = pd.read_csv(train_path)
df_test  = pd.read_csv(test_path)

print(f"Train shape: {df_train.shape}")
print(f"Test shape:  {df_test.shape}")
print(f"\nColumns: {list(df_train.columns)}")

# Features and targets
FEATURE_COLS = ['temperature', 'vibration', 'pressure', 'current',
                'rpm', 'humidity', 'voltage', 'acoustic_emission']

TARGET_CLASS = 'fault_severity'   # 0=OK, 1=WARNING, 2=FAULT
TARGET_REG   = 'remaining_useful_life'  # hours until failure

X_train = df_train[FEATURE_COLS].values
y_cls_train = df_train[TARGET_CLASS].values
y_reg_train = df_train[TARGET_REG].values

X_test  = df_test[FEATURE_COLS].values
y_cls_test  = df_test[TARGET_CLASS].values
y_reg_test  = df_test[TARGET_REG].values

# ============================================================
# SECTION 1: DATA EXPLORATION [30 points]
# ============================================================
print("\n" + "=" * 60)
print("SECTION 1: Data Exploration")
print("=" * 60)

# TODO 1.1 [5 pts]: Print basic statistics
# - Shape, dtypes, basic descriptive stats (.describe())
# - Check for missing values
# YOUR CODE HERE:
print("\nTODO 1.1: Print basic statistics")
print(df_train.describe())

# TODO 1.2 [5 pts]: Class distribution
# - How many OK / WARNING / FAULT samples?
# - Is the dataset imbalanced?
# YOUR CODE HERE:
print("\nTODO 1.2: Class distribution")
print(df_train[TARGET_CLASS].value_counts())

# TODO 1.3 [10 pts]: Visualize feature distributions
# - Plot histograms for each feature, colored by fault_severity
# - Save to output/eda_distributions.png
# YOUR CODE HERE:
print("\nTODO 1.3: Plot feature distributions (save to output/)")

# TODO 1.4 [10 pts]: Correlation analysis
# - Compute correlation matrix
# - Which features are most correlated with fault_severity?
# - Plot heatmap and save to output/eda_correlation.png
# YOUR CODE HERE:
print("\nTODO 1.4: Correlation analysis")
print(df_train[FEATURE_COLS + [TARGET_CLASS]].corr()[TARGET_CLASS].sort_values())

# ============================================================
# SECTION 2: PREPROCESSING [20 points]
# ============================================================
print("\n" + "=" * 60)
print("SECTION 2: Preprocessing")
print("=" * 60)

# TODO 2.1 [5 pts]: Handle missing values
# - Check if there are any
# - Fill with appropriate strategy (mean, median, or drop)
# YOUR CODE HERE:
print("\nTODO 2.1: Check missing values")
print(df_train[FEATURE_COLS].isnull().sum())

# TODO 2.2 [10 pts]: Scale features
# - Create a StandardScaler
# - Fit on TRAINING data only
# - Transform both train and test
# YOUR CODE HERE:
print("\nTODO 2.2: Scale features")
scaler = StandardScaler()
# X_train_scaled = ...
# X_test_scaled  = ...
X_train_scaled = scaler.fit_transform(X_train)  # starter (already done)
X_test_scaled  = scaler.transform(X_test)        # starter (already done)
print("Scaler fitted. Train mean (approx 0):", X_train_scaled.mean(axis=0).round(3))

# TODO 2.3 [5 pts]: Split training data into train + validation
# - Use 80% for training, 20% for validation
# YOUR CODE HERE:
X_tr, X_val, y_cls_tr, y_cls_val, y_reg_tr, y_reg_val = train_test_split(
    X_train_scaled, y_cls_train, y_reg_train,
    test_size=0.2, random_state=42, stratify=y_cls_train
)
print(f"Train: {len(X_tr)}, Val: {len(X_val)}")

# ============================================================
# SECTION 3: CLASSICAL ML [40 points]
# ============================================================
print("\n" + "=" * 60)
print("SECTION 3: Classical ML")
print("=" * 60)

# TODO 3.1 [15 pts]: Classification (predict fault_severity)
# - Train RandomForestClassifier and one other model of your choice
# - Cross-validate with 5-fold CV on training data
# - Report: accuracy, F1 (macro and per-class), confusion matrix
# YOUR CODE HERE:
print("\nTODO 3.1: Train classifiers")

# Starter: Random Forest
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_tr, y_cls_tr)
y_cls_pred_rf = rf_clf.predict(X_test_scaled)
print(f"Random Forest test accuracy: {(y_cls_pred_rf == y_cls_test).mean():.4f}")
print("TODO: Add your second classifier and full evaluation report")

# TODO 3.2 [15 pts]: Regression (predict remaining_useful_life)
# - Train RandomForestRegressor and one other model
# - Evaluate with R² and RMSE on test set
# YOUR CODE HERE:
print("\nTODO 3.2: Train regressors")
rf_reg = RandomForestRegressor(n_estimators=100, random_state=42)
rf_reg.fit(X_tr, y_reg_tr)
y_reg_pred_rf = rf_reg.predict(X_test_scaled)
print(f"Random Forest R²:   {r2_score(y_reg_test, y_reg_pred_rf):.4f}")
print(f"Random Forest RMSE: {np.sqrt(mean_squared_error(y_reg_test, y_reg_pred_rf)):.2f} hours")
print("TODO: Add your second regressor and full evaluation")

# TODO 3.3 [10 pts]: Feature importance
# - Which sensors matter most for fault detection?
# - Plot feature importances and save to output/feature_importance.png
# YOUR CODE HERE:
print("\nTODO 3.3: Feature importance analysis")
importances = rf_clf.feature_importances_
for feat, imp in sorted(zip(FEATURE_COLS, importances), key=lambda x: -x[1]):
    print(f"  {feat:25s}: {imp:.4f}")

# ============================================================
# SECTION 4: DEEP LEARNING (MLP) [50 points]
# ============================================================
print("\n" + "=" * 60)
print("SECTION 4: Deep Learning — MLP")
print("=" * 60)

# TODO 4.1 [20 pts]: Build and train MLP for CLASSIFICATION
# - Architecture: at least 2 hidden layers, ReLU activations
# - Use CrossEntropyLoss
# - Train with Adam, include validation monitoring
# - Plot training loss curve
# YOUR CODE HERE:

class FaultClassifierMLP(nn.Module):
    """TODO: Implement your fault classifier network."""
    def __init__(self):
        super().__init__()
        # TODO: Define layers
        # self.network = nn.Sequential(...)
        pass
    
    def forward(self, x):
        # TODO: Define forward pass
        pass

print("\nTODO 4.1: Build and train classification MLP")
print("Implement FaultClassifierMLP, train it, and evaluate on test set")

# TODO 4.2 [20 pts]: Train MLP for REGRESSION (predict remaining_useful_life)
# - Use MSELoss
# - Report R² and RMSE on test set
# YOUR CODE HERE:
print("\nTODO 4.2: Build and train regression MLP")

# TODO 4.3 [10 pts]: Compare PyTorch MLP vs sklearn RandomForest
# - Which is better for classification? For regression?
# - Discuss why (overfitting? dataset size? feature complexity?)
# YOUR CODE HERE:
print("\nTODO 4.3: Compare ML approaches")

# ============================================================
# SECTION 5: EVALUATION & COMPARISON [30 points]
# ============================================================
print("\n" + "=" * 60)
print("SECTION 5: Model Comparison")
print("=" * 60)

# TODO 5.1 [15 pts]: Create a summary comparison table
# - All classification models: accuracy, macro-F1, per-class F1
# - All regression models: R², RMSE
# - Print as a formatted table
# YOUR CODE HERE:
print("\nTODO 5.1: Summary comparison table")
print("| Model                | Accuracy | Macro-F1 |")
print("|----------------------|----------|----------|")
print("| RandomForest (clf)   |   ?      |   ?      |")
print("| Your 2nd classifier  |   ?      |   ?      |")
print("| PyTorch MLP          |   ?      |   ?      |")

# TODO 5.2 [15 pts]: Confusion matrix for best classification model
# - Plot confusion matrix heatmap with class labels (OK/WARNING/FAULT)
# - Save to output/confusion_matrix.png
# YOUR CODE HERE:
print("\nTODO 5.2: Plot confusion matrix for best model")

# ============================================================
# SECTION 6: INTERPRETATION [30 points]
# ============================================================
print("\n" + "=" * 60)
print("SECTION 6: Engineering Interpretation")
print("=" * 60)

# TODO 6.1 [15 pts]: Actionable findings
# Write as print statements or comments answering:
#   - Which sensors are most critical for predicting failure?
#   - What sensor pattern characterizes a FAULT condition?
#   - At what remaining_useful_life threshold should maintenance be triggered?
#   - Which model would you deploy in production and why?
print("\nTODO 6.1: Engineering insights")
print("  Critical sensors: ...")
print("  FAULT pattern: ...")
print("  Maintenance threshold: ...")
print("  Recommended model: ...")

# TODO 6.2 [15 pts]: Limitations and future work
#   - What are the limitations of your model?
#   - What additional data would improve performance?
#   - How would you deploy this in a real factory?
print("\nTODO 6.2: Limitations and future work")
print("  Limitations: ...")
print("  Additional data needed: ...")
print("  Deployment plan: ...")

print("\n" + "=" * 60)
print("CAPSTONE COMPLETE — Check output/ for all saved figures")
print("Submit: this file (completed) + a brief written report")
print("=" * 60)
